x=float(input('Digite uma medida em metros:'))
print('dm= {}'.format(x*10))
print('cm= {}'.format(x*100))
print('mm= {}'.format(x*1000))
print('m= {}'.format(x))
print('dam= {}'.format(x/10))
print('hm= {}'.format(x/100))
print('km= {}'.format(x/1000))
